services:
	-type:web
	 name:ml-flask-api
	env: python
	plan: free
	buildCommand: "pip install -r requirements.txt"
	startCommand: "gunicorn app:app --bind 0.0.0.0:$port"
	autodeploy: false #we'll trigger deploy via github actions